# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1555047694e2870e3be1208d54a8b73f14a922dedd82fbd2b88350dd9a7044367ebed3a639ea18a5ee3fc748ee5a119e1547cf6d95c368261c7f0ef21e2837d1

test:
  secret_key_base: fb0ce581a543a98ce1a603af1d1698064fcd9762b9bc3bd9f342d41ac29ae2f29f7b6952d4d16d3513c9a7e063d86b38e7b37a1823c104911cb9cbb154597eb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
